### PR TITLE
add lfp, vanadium, lair, pair battery technologies as storage units

### PR DESCRIPTION
**Pull request by virio-andreyana**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kunde/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kunde/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Technology | Parameter | Unit |   | PyPSA technology name | PyPSA technology name | PyPSA technology name | Proposed PyPSA name
-- | -- | -- | -- | -- | -- | -- | --
Li-ion | Duration | h | 1 |   |   |   | lfp
  | CAPEX_Storage | EUR/kW | 81553.4846 | Lithium-Ion-LFP-bicharger |   |   | lfp
  | OPEX_Storage | EUR/kWh | 236482.8109 | Lithium-Ion-LFP-store |   |   | lfp
  | FOM | %/yr | 2.1645 | Lithium-Ion-LFP-store | Lithium-Ion-LFP-bicharger |   | lfp
  | Efficiency_Charge | per unit | 0.9193 | Lithium-Ion-LFP-bicharger |   |   | lfp
  | Efficiency_Discharge | per unit | 0.9193 | Lithium-Ion-LFP-bicharger |   |   | lfp
Vanadium   Redox Flow | Duration | h | 10 |   |   |   | vanadium
  | CAPEX_Storage | EUR/kW | 129023.0526 | Vanadium-Redox-Flow-bicharger |   |   | vanadium
  | OPEX_Storage | EUR/kWh | 258072.8586 | Vanadium-Redox-Flow-store |   |   | vanadium
  | FOM | %/yr | 2.674 | Vanadium-Redox-Flow-store | Vanadium-Redox-Flow-bicharger |   | vanadium
  | Efficiency_Charge | per unit | 0.806 | Vanadium-Redox-Flow-bicharger |   |   | vanadium
  | Efficiency_Discharge | per unit | 0.806 | Vanadium-Redox-Flow-bicharger |   |   | vanadium
Liquid Air | Duration | h | 12 |   |   |   | lair
  | CAPEX_Storage | EUR/kW | 159004.771 | Liquid-Air-charger | Liquid-Air-discharger |   | lair
  | OPEX_Storage | EUR/kWh | 809738.2619 | Liquid-Air-store |   |   | lair
  | FOM | %/yr | 1.208 | Liquid-Air-charger | Liquid-Air-discharger | Liquid-Air-store | lair
  | Efficiency_Charge | per unit | 0.99 | Liquid-Air-charger |   |   | lair
  | Efficiency_Discharge | per unit | 0.55 | Liquid-Air-discharger |   |   | lair
Adiabatic   CAES | Duration | h | 24 |   |   |   | pair
  | CAPEX_Storage | EUR/kW | 946180.9426 | Compressed-Air-Adiabatic-bicharger |   |   | pair
  | OPEX_Storage | EUR/kWh | 5448.7894 | Compressed-Air-Adiabatic-store |   |   | pair
  | FOM | %/yr | 1.3565 | Compressed-Air-Adiabatic-store | Compressed-Air-Adiabatic-bicharger |   | pair
  | Efficiency_Charge | per unit | 0.7211 | Compressed-Air-Adiabatic-bicharger |   |   | pair
  | Efficiency_Discharge | per unit | 0.7211 | Compressed-Air-Adiabatic-bicharger |   |   | pair

</body>

</html>

## TODO list:

- [ ] Test config.form.yaml
- [ ] Include those battery technologies as store and link as well?
- [ ] add colouring scheme

### CODE REVIEW

**Review by daniel-rdt — COMMENTED** [review]
Looking nice. Good and efficient job @virio-andreyana!! I tested it locally and it ran through all the way with solving.
Only left a few minor comments/suggestions that you can go over. One general thing that I would add is updating the `doc/configtables` descriptions for the changes that were made regarding the config file. Otherwise, can be merged then in my opinion

**Comment by daniel-rdt** [comment]
We will need to make sure that the adjusted efficiency for Adiabatic CAES at 77,45% (?) makes it into our model @virio-andreyana

**Comment by daniel-rdt** [comment]
@virio-andreyana Lily just answered this morning that they want to stick to the default `battery storage and inverter` values for Li-Ion. I think, we should still keep the lfp functionality but need to adjust it in the `config.form.yaml` which one we are using.

**Comment by virio-andreyana** [comment]
> We will need to make sure that the adjusted efficiency for Adiabatic CAES at 77,45% (?) makes it into our model @virio-andreyana

I forgot, is that round trip or the efficiency for each charge and discharge? To prevent changing the cost table, we can put this in the config based on https://pypsa-eur.readthedocs.io/en/latest/configuration.html#adjustments. I need to test it first but what do you think?

```yaml
adjustments:
  sector:
    absolute:
      StorageUnit:
        pair:
          efficiency_store: 0.7745
          efficiency_dispatch: 0.7745
```

**Comment by daniel-rdt** [comment]
> > We will need to make sure that the adjusted efficiency for Adiabatic CAES at 77,45% (?) makes it into our model @virio-andreyana
> 
> I forgot, is that round trip or the efficiency for each charge and discharge? To prevent changing the cost table, we can put this in the config based on https://pypsa-eur.readthedocs.io/en/latest/configuration.html#adjustments. I need to test it first but what do you think?
> 
> ```yaml
> adjustments:
>   sector:
>     absolute:
>       StorageUnit:
>         pair:
>           efficiency_store: 0.7745
>           efficiency_dispatch: 0.7745
> ```

Nice, good idea. I am not quite sure though if that works with sector-coupled models, i.e. elements added in `prepare_sector_network`. We can indeed even use the overwrite functionality that I am implementing in this PR based on the PyPSA-Earth implementation and the EEE project: https://github.com/open-energy-transition/pypsa-eur/pull/23
This would also allow to specify in the `costs` tab of the config:
```
costs:
   efficiency:
       Compressed-Air-Adiabatic-bicharger: 0.7745
```

**Comment by virio-andreyana** [comment]
@daniel-rdt  Well the function that enables that adjustment is `maybe_adjust_costs_and_potentials()` which is already used in `prepare_sector_network.py`. 

I find your idea more elegant, but it depends on how soon will https://github.com/open-energy-transition/pypsa-eur/pull/23 be merged. When do we want to start an initial scenario run?

**Comment by daniel-rdt** [comment]
> @daniel-rdt Well the function that enables that adjustment is `maybe_adjust_costs_and_potentials()` which is already used in `prepare_sector_network.py`.
> 
> I find your idea more elegant, but it depends on how soon will #23 be merged. When do we want to start an initial scenario run?

Cool, the let's go the overwrites way. I want to get #23 merged today. I still need to make some minor adjustments though. My plan for the initial main scenario runs is to start this tomorrow before the weekend. Then we can have a look Monday, make some adjustments if necessary and have another run on Tuesday if necessary

**Pull request merged**
